### ISSUE TITLE
How to specify to eeacms/haproxy a different web app port?

### ISSUE THREAD

**Issue by cesarhernandezgt** [eea/eea.docker.haproxy#2]
If the web application uses a port different than 80 (for example 8080), How you can specify to eeacms/haproxy to listen 8080 in all webapp Services that will be scaled using for example `docker-compose scale webapp:3`?

```
haproxy:
  restart: always
  image: eeacms/haproxy
  links:
  - webapp
  ports:
  - "80:80"
  - "1936:1936"

webapp:
  restart: always
  image: tomcat/myapp 
  ports:
  -"8080"
```

**Comment by avoinea** [comment]
@cesarhernandezgt is not possible yet, but I'm working on it. It will be in place these days.

**Comment by avoinea** [comment]
@cesarhernandezgt fixed in the latest release. Just use `BACKENDS_PORT` env

See tags: 
* `:latest`
* `:1.6`

Please note that these latest images run haproxy on default port `5000` inside container instead of `80`

**Comment by lamarios** [comment]
I'm a bit confuse how to set this up,  My web apps running on port 4567 and i want the haproxy to run on port 8000 (balancing on port 4567) how should i do ?

My config is like this but i can't get it to work

```
haproxy:
  image: eeacms/haproxy
  links:
  - calculator
  ports:
  - "8000:5000"
  - "1936:1936"
  environment:
   - BACKENDS_PORT=4567
   - SERVICE_NAMES=calculator
############
## Calculators
 calculator:
  build: ./calculator/
  restart: unless-stopped
  volumes:
   - "./cache:/usr/src/app/cache"
```

**Comment by bober2000** [comment]
@lamarios if this is still actual:
`
  haproxy:
    image:  eeacms/haproxy
    depends_on:
      - calculator
    ports:
      - "8000:5000"
      - "1936:1936"
    environment:
      BACKENDS: "calculator:4567"
      DNS_ENABLED: "true"
`

**Comment by rakeshnpatel** [comment]
@bober2000 I tried above option, but the HA Proxy does not show petclinicweb service as registered. in the localhost:1936 it shows the status as DOWN. anything I am missing ?
My docker-compose file:
```
version: '2'
services:
  haproxy:
    image: eeacms/haproxy
    depends_on:
      - petclinicweb
    ports:
      - "8080:5000"
      - "1936:1936"
    environment:
      BACKENDS: "petclinicweb:8080"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"
  petclinicweb:
    image: petclinic-web:latest
    ports:
    - '8080'
```

<img width="1428" alt="screenshots 2018-10-24 at 4 15 07 pm" src="https://user-images.githubusercontent.com/16001954/47458640-0b5e3100-d7a8-11e8-9507-560cdefbec91.png">
