### ISSUE TITLE
Logs error

### ISSUE THREAD

**Issue by lgaticaq** [eea/eea.docker.haproxy#4]
Hello my docker-compose.yml is:

``` yml
web:
  build: .
  env_file: .env
  command: python drivetech/manage.py run_gunicorn -b "0.0.0.0:80" -w 3
worker:
  build: .
  env_file: .env
  command: python drivetech/manage.py celery worker -B -l info
haproxy:
  image: eeacms/haproxy
  links:
    - web
  ports:
    - "80:5000"
    - "1936:1936"
  environment:
    - SERVICE_NAMES=web
    - BACKENDS_PORT=80
```

And this is error

``` sh
haproxy_1  | syslog service cannot be started: [Errno 13] Permission denied: '/dev/log'
haproxy_1  | command service cannot be started: [Errno 13] Permission denied
haproxy_1  | Setting up watches.
haproxy_1  | Watches established.
haproxy_1  | Request made to kill system.
haproxy_1  | /etc/hosts CLOSE_WRITE,CLOSE 
haproxy_1  | syslog service cannot be started: [Errno 13] Permission denied: '/dev/log'
haproxy_1  | command service cannot be started: [Errno 13] Permission denied
haproxy_1  | Setting up watches.
haproxy_1  | Watches established.
```
